USE fit_airline;

insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Sightseeing tour');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Dubai International Airport', 'Dinner reservation');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Los Angeles International Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Shopping at local market');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Heathrow Airport', 'Flight to Paris');
insert into AEROPORTO (nome_aeroporto, cidade) values ('Tokyo Haneda Airport', 'Hotel check-in');
insert into AEROPORTO (nome_aeroporto, cidade) values ('John F. Kennedy International Airport', 'Dinner reservation');
