use fit_airline;

insert into TIPO_TICKET (n_ticket, tipo_ticket) values (211,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (285,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (43,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (81,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (34,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (225,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (274,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (50,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (422,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (415,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (46,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (418,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (363,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (20,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (305,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (199,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (311,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (144,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (387,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (191,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (349,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (90,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (353,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (367,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (64,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (11,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (88,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (316,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (264,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (295,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (385,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (149,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (215,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (261,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (436,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (482,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (63,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (76,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (97,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (195,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (459,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (270,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (196,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (273,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (78,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (429,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (114,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (132,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (303,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (66,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (198,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (456,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (260,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (374,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (327,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (42,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (3,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (441,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (204,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (460,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (452,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (221,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (216,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (153,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (392,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (55,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (457,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (434,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (126,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (40,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (5,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (258,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (268,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (450,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (226,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (498,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (469,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (168,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (32,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (412,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (56,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (281,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (335,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (143,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (178,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (146,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (181,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (231,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (31,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (72,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (15,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (125,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (476,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (113,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (65,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (445,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (89,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (12,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (172,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (373,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (375,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (115,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (17,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (340,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (280,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (51,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (396,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (38,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (393,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (416,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (492,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (446,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (190,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (14,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (259,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (292,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (473,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (411,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (87,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (442,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (478,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (471,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (85,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (286,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (71,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (104,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (248,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (293,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (420,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (79,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (94,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (344,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (202,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (402,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (155,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (448,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (249,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (372,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (68,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (109,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (256,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (454,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (52,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (438,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (437,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (426,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (157,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (147,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (59,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (159,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (62,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (245,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (4,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (105,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (161,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (197,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (381,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (500,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (26,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (399,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (154,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (407,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (9,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (272,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (343,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (371,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (1,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (176,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (294,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (296,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (490,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (433,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (142,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (206,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (13,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (284,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (366,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (239,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (424,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (83,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (57,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (447,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (254,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (205,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (481,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (337,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (440,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (148,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (384,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (67,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (250,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (263,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (175,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (397,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (488,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (467,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (477,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (362,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (466,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (91,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (167,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (107,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (336,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (458,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (29,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (318,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (45,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (240,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (247,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (390,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (101,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (423,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (194,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (179,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (134,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (394,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (28,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (338,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (151,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (16,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (233,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (288,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (324,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (348,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (200,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (359,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (185,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (171,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (356,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (138,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (127,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (238,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (124,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (443,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (160,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (217,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (244,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (182,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (183,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (173,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (276,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (400,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (246,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (39,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (230,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (242,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (499,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (140,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (332,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (212,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (219,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (346,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (99,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (432,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (428,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (326,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (137,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (464,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (493,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (320,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (312,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (308,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (365,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (401,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (345,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (404,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (453,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (321,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (427,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (267,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (165,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (220,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (465,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (213,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (300,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (354,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (189,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (224,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (103,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (325,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (405,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (377,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (203,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (307,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (322,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (121,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (135,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (74,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (262,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (463,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (30,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (313,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (232,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (334,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (208,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (461,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (60,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (289,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (352,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (435,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (141,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (389,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (95,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (22,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (234,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (391,'person with disability');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (472,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (315,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (361,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (77,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (120,'elderly');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (355,'child');
insert into TIPO_TICKET (n_ticket, tipo_ticket) values (489,'child');