use fit_airline;

insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (226,215,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (259,192,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (401,63,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (24,437,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (435,149,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (357,462,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (293,185,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (155,97,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (413,19,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (280,490,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (126,287,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (349,222,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (311,360,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (200,428,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (426,181,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (182,303,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (61,188,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (303,103,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (493,430,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (62,164,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (188,224,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (461,236,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (220,500,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (205,226,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (59,137,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (422,443,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (254,460,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (180,109,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (318,240,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (471,308,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (45,369,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (307,53,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (383,161,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (197,391,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (203,78,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (113,225,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (300,143,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (436,23,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (366,132,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (456,380,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (142,261,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (454,269,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (85,208,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (476,209,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (116,389,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (331,16,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (376,42,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (464,37,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (181,124,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (247,147,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (385,395,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (130,248,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (377,120,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (242,68,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (120,107,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (335,476,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (150,323,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (63,310,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (148,34,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (262,447,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (358,272,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (465,468,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (34,422,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (156,60,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (450,27,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (172,427,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (5,400,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (232,259,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (445,104,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (171,446,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (229,404,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (41,200,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (315,361,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (186,381,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (424,80,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (18,394,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (292,90,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (423,314,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (425,387,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (390,12,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (54,433,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (239,62,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (115,474,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (314,217,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (246,146,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (257,163,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (417,383,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (128,246,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (356,336,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (469,373,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (486,289,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (14,35,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (72,497,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (325,52,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (240,108,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (233,291,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (152,205,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (187,30,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (133,482,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (38,191,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (364,1,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (248,484,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (159,194,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (92,122,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (411,86,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (330,255,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (102,382,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (79,349,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (452,219,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (42,204,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (245,230,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (489,28,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (484,495,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (298,416,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (207,245,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (110,98,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (279,407,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (482,398,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (122,111,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (29,254,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (316,174,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (350,378,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (225,295,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (386,386,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (75,189,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (448,365,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (64,121,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (362,169,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (258,221,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (480,252,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (10,467,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (87,313,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (44,397,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (6,251,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (33,491,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (48,413,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (365,478,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (210,465,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (138,335,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (185,487,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (243,315,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (161,344,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (255,2,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (35,177,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (410,46,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (339,412,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (100,41,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (163,129,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (361,364,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (56,461,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (460,359,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (23,70,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (289,184,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (123,435,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (166,110,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (32,127,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (382,83,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (381,81,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (444,196,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (352,420,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (470,347,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (139,469,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (129,7,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (284,126,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (270,429,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (282,223,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (131,195,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (136,193,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (268,307,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (378,324,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (119,301,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (106,228,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (260,61,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (94,3,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (81,210,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (387,66,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (141,130,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (71,441,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (372,229,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (478,197,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (267,235,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (447,116,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (160,483,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (112,140,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (3,51,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (416,294,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (89,170,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (354,206,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (459,432,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (475,133,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (78,330,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (333,67,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (12,134,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (340,267,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (434,71,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (214,176,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (487,94,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (105,449,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (9,201,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (272,11,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (228,457,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (389,175,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (177,64,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (271,434,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (37,257,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (407,278,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (13,305,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (86,357,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (158,96,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (68,363,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (393,298,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (77,345,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (199,112,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (276,141,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (184,448,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (396,415,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (310,312,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (342,151,'Hotel check-in');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (168,297,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (343,485,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (19,24,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (22,341,'Airport transfer');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (467,26,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (328,18,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (224,494,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (421,241,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (165,9,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (428,59,'Flight to Paris');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (285,414,'Dinner reservation');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (201,325,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (213,355,'Sightseeing tour');
insert into VOAR (n_aeronave, cod_aeroporto, itinerario) values (153,326,'Flight to Paris');
